### PR TITLE
Removed toy coordinator service

### PR DESCRIPTION
**Pull request by emulbreh**

### CODE REVIEW

**Comment by mamachanko** [comment]
If you remove `conf/simple-node.yml` let's rename `conf/local-zookeeper-rabbitmq-node.yml` to `demo-node.yml` for instance.

**Comment by emulbreh** [comment]
Renamed to sample-node.yml

**Comment by mamachanko** [comment]
Travis is breaking but doesn't add a red cross here. https://travis-ci.org/deliveryhero/lymph/pull_requests

**Comment by mamachanko** [comment]
+1

**Pull request merged**
