### PR TITLE
Forward exception information on unexpected errors

### PR DESCRIPTION
**Pull request by Drahflow**
... because it's nice when you don't have to hunt for the original Nack source.

### CODE REVIEW

**Comment by jacqueslh** [comment]
LGTM

**Comment by Menda** [comment]
It's fine :+1:

**Comment by emulbreh** [comment]
NACK intentionally doesn't contain a traceback or other error details, since you can't recover from this type of error. Why do you want it?

**Comment by Drahflow** [comment]
Traceback information is not for recovering from error, but to aid in debugging. It is helpful during development when new errors happen and also in production as one does not have to hunt through the error logs of multiple services and hope to correlate multiple errors into one narrative.

Given that this only concerns unrecoverable errors, which we don't expect too often on production, I don't see much of a downside of sending this extra info.

**Comment by Drahflow** [comment]
I made #203 so the proposed design is actually implemented and grepping the logfiles useful.

**Pull request closed without merging**
