### PR TITLE
Send notifications to lymph IRC channel

### PR DESCRIPTION
**Pull request by promulo**

### CODE REVIEW

**Comment by Menda** [comment]
There's a chat channel about Lymph? Didn't know that

**Comment by promulo** [comment]
Yes. It's in irc.freenode.net network, #lymph :)

**Comment by kpanic** [comment]
@promulo should we use http://docs.travis-ci.com/user/notifications/#IRC-notification from here
`use_notice: true` ? What do you think?

**Comment by promulo** [comment]
you're right, @kpanic I've updated the PR, thanks :)

**Comment by Menda** [comment]
There's a chat channel about Lymph? Didn't know that

:+1:

**Pull request merged**
