### PR TITLE
Fix "starting trace" message level

### PR DESCRIPTION
**Pull request by manisenkov**

### CODE REVIEW

**Comment by mouadino** [comment]
LGTM

**Comment by mamachanko** [comment]
+1

**Comment by dushyant88** [comment]
Should we maintain a changelog as we are pinning versions now?

PS: +1

**Comment by kashopi** [comment]
:+1: and :+1: to @dushyant88 's suggestion for a changelog.

**Comment by mamachanko** [comment]
@dushyant88 isn't that somewhat automatigically handled by GitHub? e.g. https://github.com/deliveryhero/lymph/compare/v0.2.0...master

**Comment by kashopi** [comment]
@mamachanko I think that @dushyant88 was trying to say was PROPER changelog :dancers: :)

**Comment by dushyant88** [comment]
@mamachanko yeah, but its nice to track what things have changed between versions. 
Something like this - https://github.com/kennethreitz/requests/blob/master/HISTORY.rst

**Pull request merged**
